WIFI_SSID = 'BacklundsGuestNet'
WIFI_PASSWORD = 'RistoNOS8'
WEBHOOK_URL = 'https://maker.ifttt.com/trigger/button_pressed/with/key/cvnTP3S5fA0NmpogPPldzq'
BUTTON_ID = 'micropython1'
LED_PIN = 2  # D4
LED2_PIN = 16  # D0
DEBUG_PIN = 14  # D5
DHT22_PIN = 4 #D2
FAHRENHEIT = False